language : python

install :
  - pip install -r requirements.txt
  - sudo apt-get install ffmpeg

script :
  - ./hotstar-playlist-downloader/hotstar-playlist-downloader.py http://www.hotstar.com/tv/mahabharat/435/seasons/season-1
